spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bankapi
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}